config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users
resources :profiles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

	  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!
  def index

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :find_profile, only: [:show, :edit, :update, :destroy]
  def index
  end

  def new
  	@profile = Profile.new
  end
  
  def create
  	@profile = current_user.build_profile(profile_params)
  	redirect_to root_path if @profile.save
  end

  def show
  	
  end

  def edit
  end

  def update
  	redirect_to profile_path(@profile.id) if @profile.update(profile_params)
  end
  def destroy
  	@profile.destroy 
  	redirect_to root_path
  end

  private
def profile_params
	params.require(:profile).permit(:user_id, :nickname, :age, :avatar)
end
def find_profile
	@profile = Profile.find_by(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<%  if current_user.profile.nil?  %>
<%= link_to "Profile", new_profile_path %>
<%  else  %>
<%= link_to "Profile", profile_path(current_user.profile) %>

<%  end  %>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>
<%= form_for @profile, url: {action: "update"} do |f| %>
nickname: <%= f.text_field :nickname %><br>
age: <%= f.text_field :age %><br>
avatar:  <%= f.file_field :avatar %><br>
<%= f.submit %>


<% end %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>
<%= form_for @profile, url: {action: "create"} do |f| %>
nickname: <%= f.text_field :nickname %><br>
age: <%= f.text_field :age %><br>
avatar:  <%= f.file_field :avatar %><br>
<%= f.submit %>
<% end %>

app/views/profiles/show.html.erb
<%= image_tag @profile.avatar.url(:thumb) %>
<%= @profile.nickname %>
<%= @profile.age %>
<%= link_to "Edit", edit_profile_path %>
<%= link_to "Delete", profile_path(@profile.id), method: :delete %>